### ISSUE TITLE
DTLS client

### ISSUE THREAD

**Issue by chkr1011** [PeterWaher/IoTGateway#11]
Hi,
I try to communicate with my IKEA Tradfri gateway via DTLS. I already wrote a small CoAP library but I am not able to get things to work properly. When using your nugets I always get the error "no response". Unfortunately I did not find any sample which clearly shows me how to use the DTLS client properly. 

My code looks like this.

```csharp
Types.Initialize();

var ikeaGatewayEndpoint = new IPEndPoint(IPAddress.Parse("192.168.1.228"), 5684);

var udpClient = new UdpClient();
var udpCommunicationLayer = new UdpCommunicationLayer(udpClient);
var dtlsClient = new DtlsEndpoint(DtlsMode.Client, udpCommunicationLayer);
var psk = new PresharedKey(Encoding.UTF8.GetBytes("Client_identity"), Encoding.UTF8.GetBytes("KEY"));

dtlsClient.OnHandshakeSuccessful += (s, e) =>
{
    dtlsClient.SendApplicationData(buffer.ToArray(), ikeaGatewayEndpoint);
};

dtlsClient.OnHandshakeFailed += (s, e) =>
{

};

dtlsClient.StartHandshake(ikeaGatewayEndpoint, psk);

Console.ReadLine();
```

The buffer is an encoded CoAP message. The code always ends in the _OnHandshakeFailed_ event handler with the reason "Timeout. No response.".

Best regards
Christian

**Comment by PeterWaher** [comment]
Hello Christian

You can add one or more sniffers (classes implementing `Waher.Networking.ISniffer`) to the `DtlsEndpoint` to find out what happens in the DTLS layer. You can find several sniffers already in the `Waher.Networking` nuget package (in the `Waher.Networking.Sniffers` namespace).

Guessing from your message, the error can be any of:

* Wrong IP address 
* Suitable ciphers not found (you can see this by listening on the DTLS layer with sniffers)
* Badly formed CoAP payload (the `Waher.Networ.CoAP` nuget contains a CoAP client that can be used for this purpose).

For more information of these topics, and how these nugets work, see my book "Matering Internet of Things", and the corresponding repository:
https://github.com/PeterWaher/MIoT

Best regards,
Peter

**Comment by chkr1011** [comment]
Thank you for your reply. Chaning the the type initialization to:

_Types.Initialize(typeof(Waher.Security.DTLS.Ciphers.PskCipher).Assembly);_

 did the trick. 👍

**Comment by PeterWaher** [comment]
Great. Thanks for the info. Good luck on your project.
Best regards,
Peter

**Comment by chkr1011** [comment]
Hi, its me again 😄 

as I said it now works perfectly but I have a problem which I cannot fix and I don't know if I am using the library in a wrong way.

I use the send method in the following way:

```csharp
var promise = new TaskCompletionSource<bool>();

            _dtlsClient.Send(buffer.ToArray(), _connectOptions.EndPoint, _credentials, (s, e) =>
            {
                promise.TrySetResult(e.Successful);
            }, null);

            var result = await promise.Task.ConfigureAwait(false);
```

The problem is that the callback only gets invoked one time. So my task completion source never gets a result. But when setting the result right after the call to "Send" the code works perfectly. The thing is that I can send datagrams without problems when ignoring the callback but I wonder if this is correct or if the callback should be executed for every time the "Send" method is used.

Best regards
Christian
