### ISSUE TITLE
Registration from Windows Form

### ISSUE THREAD

**Issue by LumiProj** [PeterWaher/IoTGateway#12]
Hi,

I am looking to create an new account in Windows Form using C#, Is there any sample code is out here for new user registration.

Thanks

**Comment by PeterWaher** [comment]
Hello

Are you referring to creating an XMPP account on an XMPP broker, If so, you can check out the XMPP examples at the Mastering Internet of Things repository:

https://github.com/PeterWaher/MIoT

You call the `AllowRegistration()` method to allow for the creation of new accounts. The form is built by the library. Example:

```
this.xmppClient = new XmppClient(Dialog.Host, Dialog.Port, Dialog.UserName, Dialog.Password, "en", typeof(App).GetTypeInfo().Assembly)
{
	AllowCramMD5 = false,
	AllowDigestMD5 = false,
	AllowPlain = false,
	AllowScramSHA1 = true,
	AllowScramSHA256 = true
};

this.xmppClient.AllowRegistration();                	// Allows registration on servers that do not require signatures.
// this.xmppClient.AllowRegistration(Key, Secret);	// Allows registration on servers requiring a signature of the registration request.

this.xmppClient.OnStateChanged += this.TestConnectionStateChanged;
this.xmppClient.OnConnectionError += this.ConnectionError;

Log.Informational("Connecting to " + this.xmppClient.Host + ":" + this.xmppClient.Port.ToString());
this.xmppClient.Connect();
```

The form is filled in by default by the `XmppClient` library. If you want to override the default behaviour, you can provide a `OnRegistrationForm` event handler.

**Comment by LumiProj** [comment]
[WindowsFormsApp30.zip](https://github.com/PeterWaher/IoTGateway/files/4830913/WindowsFormsApp30.zip)

Hi,

I am usng opensource xmpp server I created a sample project and used the same code of registration which you provided but not able to get registration done.

I attached  a sample so can see what is the core issue.

Waiting for the reposnse.

Thanks

**Comment by PeterWaher** [comment]
You will need to use a sniffer to troubleshoot your implementation and the communication being done. You can find several in the `Waher.Networking.Sniffers` namespace. You register sniffers with the `XmppClient` object in the constructor. Support of my libraries is included in the commercial license. If you are interested in such, you can request more information at: https://waher.se/Feedback.md

**Comment by LumiProj** [comment]
Hi Awesome.

Well actually I have resolved the issue, The server which I was using in sample it does not allow registration so after changing the server details to my own hosted jabberd server  everything starts working perfectly.

Thank you a lot

I have just one more question.

Can we use this library into Xamarin Forms ?

Thanks

**Comment by PeterWaher** [comment]
Excellent. I use these libraries in Xamarin myself. You can use them in accordance with the license:
https://github.com/PeterWaher/IoTGateway#license
