### ISSUE TITLE
License Details

### ISSUE THREAD

**Issue by AtifShahzed** [PeterWaher/IoTGateway#15]
Hi,

I have sent an email few days for the details of xmpp license , Please review email and send me the details, My client is waiting for the details.

Thanks

**Comment by PeterWaher** [comment]
Dear Atif

I saw your post on GitHub, and therefore assume you did not receive the commercial license I sent to you earlier. I have resent it. Let me know if you receive it. You can also mail me at peterwaher [at] hotmail.com, to make sure I have your correct e-mail address.

Best regards,
Peter Waher
