### ISSUE TITLE
Having a hard time getting up and running

### ISSUE THREAD

**Issue by kipusoep** [PeterWaher/IoTGateway#22]
Hi,

I am currently evaluating this project for running a LWM2M server, but having a really hard time.
First the IoTGateway wouldn't start. After doing a lot of investigation, I found out it tried to bind to port 80. But I have IIS running, so it couldn't. Stopping IIS helped.
Then I needed to enter XMPP information. After searching for free public available servers, I finally found one that passed the connection (macaw.me).
The same information is **not** working in the IoTGateway client btw, it gived an error when trying to connect:
> Bad value of attribute 'from' in tag <stream:stream/> qualified by namespace 'jabber:client'

Now, I've restarted the IoTGateway and am presented with a screen to assign a Legal identity.
Whatever I try, I can't get past this screen. If I click the Next button, I get this error:
> File not found: /Settings/ConfigComplete

It doesn't matter if I enter identity information or not.

So I'm pretty much getting annoyed by these issues, do you know what's wrong?

**Comment by PeterWaher** [comment]
Hello

Most of these questions are answered in the Mastering Internet of Things book, linked to in the repository. You can also check the associated repository: https://github.com/PeterWaher/MIoT

Best regards,
Peter

**Comment by kipusoep** [comment]
So, if I understand correctly, the error `File not found: /Settings/ConfigComplete` is not an error? It's by design? Or...?

**Comment by PeterWaher** [comment]
It's probably a secondary effect of something that goes wrong earlier during start-up, so that the referenced resource does not get registered. You would see in the logs. If you provide me with your e-mail address, I can send additional info.

**Comment by kipusoep** [comment]
I only see the not found error in the logs (windows event viewer). I will provide my email address via the contact form on your website.
