### ISSUE TITLE
HttpClientHandler.AutomaticDecompression defaults to None after System.Net.Http 4.3.2

### ISSUE THREAD

**Issue by berggrenmille** [PeterWaher/IoTGateway#25]
## Problem

When creating a HttpClientHandler you can set the AutomaticDecompression for for automatic decompression of the HTTP content response. In the System.Net.Http the default has been DecompressionMethods.Gzip | DecompressionMethods.Deflate. After 4.3.2 it defaults to none.

This has affected in my experience only Android applications and leads to an exception when getting encoded responses

## Solution

Explicitly set AutomaticDecompression
In WebGetter.cs (IoTGateway/Content/Waher.Content/Getters/WebGetter.cs line 118)
change
```
			HttpClientHandler Handler = new HttpClientHandler()
			{
				AllowAutoRedirect = true,
				CheckCertificateRevocationList = true,
				ClientCertificateOptions = ClientCertificateOption.Automatic,
				ServerCertificateCustomValidationCallback = Validator.RemoteCertificateValidationCallback
			};
```

to

```
			HttpClientHandler Handler = new HttpClientHandler()
			{
				AllowAutoRedirect = true,
				CheckCertificateRevocationList = true,
				ClientCertificateOptions = ClientCertificateOption.Automatic,
				ServerCertificateCustomValidationCallback = Validator.RemoteCertificateValidationCallback
                                AutomaticDecompression = DecompressionMethods.Gzip | DecompressionMethods.Deflate,
			};
```

**Comment by PeterWaher** [comment]
Thanks for the suggestion and detailed information. I've updated the code to include `AutomaticDecompression = (DecompressionMethods)(-1)` to cover for compression methods available in later .NET versions, such as Brotli (.NET 6).

I've aksi incremented the package version number of the Content library and published a new nuget with the change.
