### ISSUE TITLE
Cipher TLS_PSK_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by michielpost** [PeterWaher/IoTGateway#3]
I'm trying to use Waher.Security.DTLS for a UDP handshake, but I need TLS_PSK_WITH_AES_128_GCM_SHA256 as Cipher which is not supported by this library. I tried to add it myself, but I have no knowledge of Cipher suites. There is a base AesCcmCipher which I tried to derive from, but I need AesGcmCipher which isn't availble. Is it possible you can add this or give me directions on how I can implement this myself?

**Comment by PeterWaher** [comment]
Hello Michiel. Sure, it's possible. Let's connect over LinkedIn and Skype to discuss this further.
