### ISSUE TITLE
Can httpserver handle any dynamic request?

### ISSUE THREAD

**Issue by Airborne76** [PeterWaher/IoTGateway#5]
I'm trying to make a httpserver in Waher.Networking.HTTP. Seems it can only register and handle a static ResourceName,  does it has any way to handle a request like [ http:/ip/?a=6 ] ,then get the parameters in the request url ?

**Comment by PeterWaher** [comment]
Implement a resource by deriving from HttpSynchronousResource or HttpAsynchronousResource. You register the fixed part of the path only (which can be the root). If the resource handles sub-paths (override the HandlesSubPaths property of the resource), it will accept requests to any resource beginning with your fixed part (if the fixed part is the root, it will contain the entire path).

HTTP methods are then implemented by implementing the corresponding method interface. Example: IHttpGetMethod.

Query parameters, HTTP headers, etc,. are available in the request object (HttpRequest) to the HTTP method callbacks.
