### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sandeepmohil** [PeterWaher/IoTGateway#6]
Hi,

There is no documentation available regarding starting a LWm2m server or client.
It would be really helpful if there is some documentation available for this.

**Comment by PeterWaher** [comment]
Hello Sandeep

Example projects using the libraries to setup LWM2M clients using IPSO objects are found here (SensorLwm2m and Actuator Lwm2m projects):
https://github.com/PeterWaher/MIoT

And fully described in this book:
https://www.packtpub.com/networking-and-servers/mastering-internet-things

Best regards,
Peter
