### ISSUE TITLE
Upcoming ACME v2 Key Rollover breaking change

### ISSUE THREAD

**Issue by cpu** [PeterWaher/IoTGateway#8]
:wave: @PeterWaher 

Hi there! Thanks for writing a project that uses Let's Encrypt and ACME v2 :heart: I wanted to file an issue with you to give you a heads up about an [upcoming backwards compatibility breaking ACME change](https://community.letsencrypt.org/t/acme-v2-draft-13-compliant-key-rollover/68953) that I think may affect your project: https://github.com/PeterWaher/IoTGateway/blob/7fb8cdf36985ec5e9e025d7b9173092a05ff87e6/Security/Waher.Security.ACME/AcmeClient.cs#L486

While I was preparing the announcement about this change I did some log analysis to see which User Agents were using the Let's Encrypt ACME v2 key change endpoint. `Waher.Security.ACME` was one of the only ones I saw. Kudos for implementing the specification so thoroughly! Sorry to break your code with a protocol change :-)

**Comment by PeterWaher** [comment]
Hello Daniel. Thanks for reaching out and the heads-up. I've now updated the library to support the draft 13 version of the key-change operation. I'll leave this item open, and first test against the staging endpoint tomorrow and in production on the 23rd.

**Comment by PeterWaher** [comment]
Recommended method supporting both draft 12 and 13 now implemented and tested against staging endpoint. Nuget updated. Waiting until the 23rd to remove draft 12 parameter from call and test again.

**Comment by PeterWaher** [comment]
Obsolete legacy parameter now removed from code. Tested against staging endpoint and seems to work fine. Closing issue.
