### ISSUE TITLE
Accepting invalid XMPP certificates

### ISSUE THREAD

**Issue by TrueGeek** [PeterWaher/IoTGateway#9]
I've read through the XMPP chapter in the book but I don't see this covered. I need to accept an invalid certificate - it's just a development domain. I'm getting this exception:

"Mono.Security.Interface.TlsException: CertificateUnknown"

Previously, in our .net Framework app, we used a component that had an option "AcceptAllCertificates". Is there a similar option for Waher.Networking.XMPP.XmppClient?

Thank you

**Comment by PeterWaher** [comment]
Hello

The `XmppClient` class has a `TrustServer` property. If set to `true`, the client will ignore certificate validation errors. The `XmppCredentials` class has a similar property, if instantiating an `XmppClient` object from `XmppCredentials`.

An alternative is to generate valid certificates in the development environment too. This is most easily done using certificates from an ACME-compliant CA (such as Let's Encrypt). You can use the `Waher.Security.ACME` library to automate certificate generation from code (see the [DomainConfiguration.cs](https://github.com/PeterWaher/IoTGateway/blob/master/Waher.IoTGateway/Setup/DomainConfiguration.cs) file for an example how to do this). You can also use the `Waher.Utility.ACME` utility in this repository (or any of a large set of ACME utilities) to do the same from command-line.
